name: fooldolx_app
description: FoolDolx - Food delivery & social app (full scaffold)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.23.0
  cloud_firestore: ^5.16.0
  firebase_auth: ^5.16.0
  firebase_storage: ^11.2.0
  video_player: ^2.6.0
  lottie: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/animations/
